version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: lodash
    versions:
    - 4.17.20
